Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('pi = ',np.pi)
print('e = ',np.e)
print('euler gamma = ',np.euler_gamma)

print('infinity = ',np.Inf)
print('infinity = ',np.Infinity)
print('infinity = ',np.inf)
print('infinity = ',np.infty)
print('positive infinity = ',np.PINF)
print('negative infinity = ',np.NINF)

print('positive zero = ',np.PZERO)
print('negative zero = ',np.NZERO)

print('nan = ',np.nan)
print('nan = ',np.NAN)
print('nan = ',np.NaN)

print('None/newaxis = ',np.newaxis)
------------------

----- stdout -----
pi =  3.141592653589793
e =  2.718281828459045
euler gamma =  0.5772156649015329
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[12], line 5[0m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124me = [39m[38;5;124m'[39m,np[38;5;241m.[39me)
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124meuler gamma = [39m[38;5;124m'[39m,np[38;5;241m.[39meuler_gamma)
[0;32m----> 5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124minfinity = [39m[38;5;124m'[39m,[43mnp[49m[38;5;241;43m.[39;49m[43mInf[49m)
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124minfinity = [39m[38;5;124m'[39m,np[38;5;241m.[39mInfinity)
[1;32m      7[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124minfinity = [39m[38;5;124m'[39m,np[38;5;241m.[39minf)

File [0;32m/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/numpy/__init__.py:400[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    397[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr], name[38;5;241m=[39m[38;5;28;01mNone[39;00m)
[1;32m    399[0m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __expired_attributes__:
[0;32m--> 400[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m    401[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m`np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[38;5;124m` was removed in the NumPy 2.0 release. [39m[38;5;124m"[39m
[1;32m    402[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m__expired_attributes__[attr][38;5;132;01m}[39;00m[38;5;124m"[39m,
[1;32m    403[0m         name[38;5;241m=[39m[38;5;28;01mNone[39;00m
[1;32m    404[0m     )
[1;32m    406[0m [38;5;28;01mif[39;00m attr [38;5;241m==[39m [38;5;124m"[39m[38;5;124mchararray[39m[38;5;124m"[39m:
[1;32m    407[0m     warnings[38;5;241m.[39mwarn(
[1;32m    408[0m         [38;5;124m"[39m[38;5;124m`np.chararray` is deprecated and will be removed from [39m[38;5;124m"[39m
[1;32m    409[0m         [38;5;124m"[39m[38;5;124mthe main namespace in the future. Use an array with a string [39m[38;5;124m"[39m
[1;32m    410[0m         [38;5;124m"[39m[38;5;124mor bytes dtype instead.[39m[38;5;124m"[39m, [38;5;167;01mDeprecationWarning[39;00m, stacklevel[38;5;241m=[39m[38;5;241m2[39m)

[0;31mAttributeError[0m: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

